# Generated by Django 3.2 on 2021-06-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210615_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcommittee',
            name='category',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mainpage.category'),
        ),
        migrations.AlterField(
            model_name='feedbackcommittee',
            name='status',
            field=models.IntegerField(choices=[(0, 'Оформлена'), (1, 'Принята')], default=0),
        ),
    ]
