# Generated by Django 3.2 on 2021-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_feedbackcommittee_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackcommittee',
            name='phone',
        ),
        migrations.AddField(
            model_name='feedbackcommittee',
            name='text',
            field=models.TextField(default='', max_length=100, verbose_name='Телефон'),
        ),
    ]
