# Generated by Django 3.2 on 2021-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_feedbackcommittee_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcommittee',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Телефон'),
        ),
    ]
