# Generated by Django 3.2 on 2021-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Наименование'),
        ),
    ]
