# Generated by Django 3.2 on 2021-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_alter_price_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Стоимость обучения'),
        ),
    ]
