# Generated by Django 3.2 on 2021-06-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_alter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='forms',
            field=models.CharField(choices=[('Заочная', 'Заочная'), ('Очно-заочная', 'Очно-заочная'), ('Очная форма', 'Очная форма')], default='Очная форма', max_length=100, verbose_name='Форма обучния'),
        ),
    ]
